format = """
[](#9A348E)\
$os\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
$git_state\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$dotnet\
[](fg:#86BBD8)\
$docker_context\
$fill\
$time\
$line_break\
$character
"""

[fill]
symbol = ' '
style = 'bold green'

[character]
success_symbol = '[❯](bold fg:#86BBD8)'
error_symbol = '[❯](bold fg:#DA627D)'

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E fg:#1d1f21"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E  fg:#1d1f21"
disabled = true # Disabled by default

[directory]
style = "bg:#DA627D fg:#1d1f21"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#86BBD8 fg:#1d1f21"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A fg:#1d1f21"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#86BBD8 fg:#1d1f21"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8 fg:#1d1f21"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FCA17D fg:#1d1f21"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D fg:#1d1f21"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8 fg:#1d1f21"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8 fg:#1d1f21"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8 fg:#1d1f21"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8 fg:#1d1f21"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8 fg:#1d1f21"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#86BBD8 fg:#1d1f21"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8 fg:#1d1f21"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[dotnet]
style = "bg:#86BBD8 fg:#1d1f21"
symbol= " "
format = '[$symbol ($version) 󰓾 ($tfm)]($style)'
heuristic = true

[git_state]
style = "bg:#FCA17D fg:#1d1f21"
format = '[\($state( $progress_current of $progress_total)\)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#c5c8c6"
format = '[ $time ]($style)'
